meta:
  url: /
brand:
  text: Project Docs
  color: "#0871ab"
  parent:
    text: Nop
    url: https://nop-platform.gitee.io
copyright:
  owner:
    text: Nop 社区
    url: https://nop-platform.gitee.io
  period:
    start: 2024
  provider: false
header:
  navbar:
    placement: right
social:
  share: false

# copied from `hexo-theme-lime`
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
